/**
 * OSEM Medication Chart Generator
 * Version: PDF-safe + real-time progress
 *
 * DESIGN RULE
 * -----------
 * The generated medication chart must preserve the Chart Template.
 *
 * The DATE cells on the right side of the chart are populated with blank
 * serving cells and "xxxx" on non-serving / invalid days.
 *
 * PDF generation is intentionally NOT duplicated here.
 * generateMedicationChartPdf() / generateBranchMedicationChartPdf()
 * remain in PDFengine.gs and consume the returned report.sheets.
 *
 * This file therefore only:
 *   1. Reads the resident medication orders.
 *   2. Copies the existing Chart Template.
 *   3. Replaces the template placeholders.
 *   4. Adds medication rows while preserving the template formatting.
 *   5. Returns the generated sheet objects to PDFengine.gs.
 *   6. Updates the live progress from 15% -> 50% during chart generation.
 */

// ============================================================
// PUBLIC: SINGLE RESIDENT / BRANCH SHARED GENERATOR
// ============================================================

function generateResidentMedicationCharts(
  residentID,
  year,
  month,
  executionId,
  branchProgressState
) {
  residentID = String(residentID || "").trim();
  year = Number(year);
  month = Number(month);
  executionId = String(executionId || "").trim();

  if (!residentID) {
    throw new Error("ResidentID is required.");
  }

  if (!Number.isFinite(year) || year < 2000) {
    throw new Error("Invalid chart year: " + year);
  }

  if (!Number.isFinite(month) || month < 1 || month > 12) {
    throw new Error("Invalid chart month: " + month);
  }

  if (!executionId) {
    executionId = Utilities.getUuid();
  }

  var resident = getResident(residentID);

  if (!resident) {
    throw new Error("Resident not found: " + residentID);
  }

  var branchMode = !!branchProgressState;

  // ----------------------------------------------------------
  // REAL-TIME PROGRESS
  // 15% = chart stage begins
  // We avoid excessive progress writes because each write can
  // add server latency.
  // ----------------------------------------------------------
  if (!branchMode) {
    setGenerationProgress(
      executionId,
      15,
      "Loading medication orders for " +
        String(resident.Residents || residentID) +
        "..."
    );
  }

  SpreadsheetApp.flush();

  // ----------------------------------------------------------
  // Load regular medication preparation sessions.
  // getPreparationSessions() already groups regular medication
  // by administration time and excludes PRN medication.
  // ----------------------------------------------------------
  var sessions = getPreparationSessions(residentID) || [];

  // PRN medication is generated by the existing PRN generator.
  var prnMedications = getResidentPRNMedication(residentID) || [];

  var totalRegularPages = sessions.length;

  // PRN_PER_PAGE already belongs to the existing PRN module.
  var totalPRNPages = 0;

  if (prnMedications.length > 0) {
    totalPRNPages = Math.ceil(
      prnMedications.length / PRN_PER_PAGE
    );
  }

  var totalPages =
    totalRegularPages + totalPRNPages;

  if (totalPages <= 0) {
    throw new Error(
      "No medication chart pages found for " +
      String(resident.Residents || residentID) +
      "."
    );
  }

  if (!branchMode) {
    setGenerationProgress(
      executionId,
      18,
      "Medication orders loaded. Preparing chart pages..."
    );
  }

  var generatedSheets = [];

  // ==========================================================
  // REGULAR MEDICATION CHARTS
  // ==========================================================

  for (var i = 0; i < sessions.length; i++) {
    var session = sessions[i];

    // Progress BEFORE the page is created.
    if (!branchMode) {
      var before = calculateMedicationChartProgress(
        i,
        totalPages
      );

      setGenerationProgress(
        executionId,
        before,
        "Preparing " +
          String(
            session.title ||
            session.time ||
            "Medication Preparation"
          ) +
          "..."
      );
    } else {
      setGenerationProgress(
        executionId,
        calculateMedicationChartProgress(
          branchProgressState.completedPages,
          branchProgressState.totalPages
        ),
        "Preparing " +
          String(
            session.title ||
            session.time ||
            "Medication Preparation"
          ) +
          " for " +
          String(resident.Residents || residentID) +
          "...",
        {
          residentNumber:
            branchProgressState.residentNumber,
          totalResidents:
            branchProgressState.totalResidents
        }
      );
    }

    SpreadsheetApp.flush();

    var sheet = createRegularMedicationChartPage(
      resident,
      session,
      year,
      month,
      executionId,
      i + 1,
      totalPages
    );

    generatedSheets.push(sheet);

    // One regular page completed.
    if (branchMode) {
      branchProgressState.completedPages =
        Number(branchProgressState.completedPages || 0) + 1;
    }

    // Progress AFTER the page is created.
    if (!branchMode) {
      var completed = i + 1;

      setGenerationProgress(
        executionId,
        calculateMedicationChartProgress(
          completed,
          totalPages
        ),
        String(
          session.title ||
          session.time ||
          "Medication Preparation"
        ) +
          " completed."
      );
    }

    SpreadsheetApp.flush();
  }

  // ==========================================================
  // PRN CHARTS
  // ==========================================================

  if (prnMedications.length > 0) {
    if (!branchMode) {
      setGenerationProgress(
        executionId,
        calculateMedicationChartProgress(
          totalRegularPages,
          totalPages
        ),
        "Preparing PRN medication chart..."
      );
    }

    SpreadsheetApp.flush();

    var completedBeforePRN = branchMode
      ? Number(branchProgressState.completedPages || 0)
      : totalRegularPages;

    // Keep the existing PRNChart.gs implementation.
    // Its signature in the current project is:
    //   resident,
    //   medications,
    //   year,
    //   month,
    //   executionId,
    //   totalPages,
    //   completedPages,
    //   branchProgressState
    //
    // This preserves the existing PRN/PDF workflow.
    var prnSheets = generatePRNCharts(
      resident,
      prnMedications,
      year,
      month,
      executionId,
      totalPages,
      completedBeforePRN,
      branchProgressState || null
    ) || [];

    for (var p = 0; p < prnSheets.length; p++) {
      generatedSheets.push(prnSheets[p]);
    }

    // PRNChart.gs normally updates branchProgressState itself.
    // For safety, if it did not, advance it here by the actual
    // number of PRN sheets returned.
    if (
      branchMode &&
      prnSheets.length > 0 &&
      branchProgressState
    ) {
      var expectedPRNCompletion =
        completedBeforePRN + prnSheets.length;

      if (
        Number(branchProgressState.completedPages || 0) <
        expectedPRNCompletion
      ) {
        branchProgressState.completedPages =
          expectedPRNCompletion;
      }
    }
  }

  // ==========================================================
  // SAFETY
  // ==========================================================

  if (generatedSheets.length === 0) {
    throw new Error(
      "Medication chart generation produced no sheets for " +
      String(resident.Residents || residentID) +
      "."
    );
  }

  // The chart-generation stage ends at 50%.
  // PDFengine.gs starts its own next stage from 50%.
  if (!branchMode) {
    setGenerationProgress(
      executionId,
      50,
      "Medication chart preparation completed."
    );
  }

  SpreadsheetApp.flush();

  return {
    resident: resident,
    residentID: residentID,
    branch: resident.Branch || "",
    year: year,
    month: month,
    executionId: executionId,
    regularPages: totalRegularPages,
    prnPages: totalPRNPages,
    totalPages: totalPages,
    sheets: generatedSheets
  };
}


// ============================================================
// PROGRESS CALCULATION
// ============================================================
// Maps chart-page completion to the 15% -> 50% stage.
//
// 0 / 10  = 15%
// 5 / 10  = 32.5%
// 10 / 10 = 50%
// ============================================================

function calculateMedicationChartProgress(
  completedPages,
  totalPages
) {
  var START = 15;
  var END = 50;

  totalPages = Number(totalPages) || 0;
  completedPages = Number(completedPages) || 0;

  if (totalPages <= 0) {
    return START;
  }

  var safeCompleted = Math.max(
    0,
    Math.min(completedPages, totalPages)
  );

  var progress =
    START +
    (safeCompleted / totalPages) *
    (END - START);

  return Math.max(
    START,
    Math.min(END, progress)
  );
}


// ============================================================
// REGULAR CHART PAGE
// ============================================================
//
// IMPORTANT:
//
// The date columns on the right are deliberately untouched.
//
// The template is responsible for:
//   - logo
//   - page title
//   - date headings
//   - borders
//   - row colours
//   - day cells for manual nursing entries
//
// The generator only fills:
//   {{RESIDENT_NAME}}
//   {{MONTH}}
//   {{SESSION_TITLE}}
//   {{NO}}
//   {{MEDICINE}}
//   {{INDICATION}}
//   {{NOTED_BY}}
// ============================================================

function createRegularMedicationChartPage(
  resident,
  session,
  year,
  month,
  executionId,
  pageNumber,
  totalPages
) {
  var ss = SpreadsheetApp.getActiveSpreadsheet();

  if (!ss) {
    throw new Error("Unable to access the source spreadsheet while creating a medication chart.");
  }

  if (
    typeof CONFIG === "undefined" ||
    !CONFIG ||
    !CONFIG.TEMPLATE_SHEET
  ) {
    throw new Error(
      "CONFIG.TEMPLATE_SHEET is not configured."
    );
  }

  var template = ss.getSheetByName(
    CONFIG.TEMPLATE_SHEET
  );

  if (!template) {
    throw new Error(
      "Medication chart template not found: " +
      CONFIG.TEMPLATE_SHEET
    );
  }

  var medications =
    (session && session.medications) || [];

  if (medications.length === 0) {
    throw new Error(
      "No regular medication found for session: " +
      String(
        (session && (session.title || session.time)) || ""
      )
    );
  }

  // ============================================================
  // FIXED TEMPLATE LAYOUT
  // ============================================================
  // The master Chart Template is deliberately used as-is.
  // Medication rows start at row 9 and are written into the
  // existing pre-formatted rows. No rows are inserted above row 9.
  // The footer/page-number position at AG32 must remain fixed.
  // ============================================================

  var medicineStartRow = 9;
  var pageNumberCell = "AG32";
  var servingTimeCell = "B6";   // B6:D7 is merged in the template.

  var medicineCell =
    medChart_findPlaceholderCell(
      template,
      "{{MEDICINE}}"
    );

  if (!medicineCell) {
    throw new Error(
      'Chart Template is missing "{{MEDICINE}}".'
    );
  }

  var noCell =
    medChart_findPlaceholderCell(
      template,
      "{{NO}}"
    );

  var indicationCell =
    medChart_findPlaceholderCell(
      template,
      "{{INDICATION}}"
    );

  var notedByCell =
    medChart_findPlaceholderCell(
      template,
      "{{NOTED_BY}}"
    );

  if (!noCell) {
    throw new Error(
      'Chart Template is missing "{{NO}}".'
    );
  }

  if (!indicationCell) {
    throw new Error(
      'Chart Template is missing "{{INDICATION}}".'
    );
  }

  if (!notedByCell) {
    throw new Error(
      'Chart Template is missing "{{NOTED_BY}}".'
    );
  }

  // Enforce the layout requested for OSEM's master chart.
  // If someone accidentally changes the template in the future,
  // fail clearly instead of silently moving the medication table.
  if (medicineCell.getRow() !== medicineStartRow) {
    throw new Error(
      'Chart Template medication row must be row 9. Current row: ' +
      medicineCell.getRow()
    );
  }

  var templateColumns = {
    no: noCell.getColumn(),
    medicine: medicineCell.getColumn(),
    indication: indicationCell.getColumn(),
    notedBy: notedByCell.getColumn()
  };

  // Date columns immediately follow the "Noted By" column.
  // This preserves the template's existing conditional formatting.
  var firstDayColumn = templateColumns.notedBy + 1;
  var numberOfDayColumns = 31;

  // The template currently provides rows 9 through 31 for medication
  // entries; row 32 is reserved for the page footer.
  var lastMedicationRow = 31;
  var maxMedicationRows =
    lastMedicationRow - medicineStartRow + 1;

  if (medications.length > maxMedicationRows) {
    throw new Error(
      "Too many medications for the Chart Template in " +
      String(session.title || session.time || "this session") +
      ". Maximum supported without changing the template layout is " +
      maxMedicationRows + "."
    );
  }

  // ============================================================
  // COPY THE TEMPLATE
  // ============================================================

  var sheet = template.copyTo(ss);

  var safeResident =
    String(
      resident.ResidentID ||
      resident.Residents ||
      "RESIDENT"
    )
      .replace(/[^A-Za-z0-9_-]/g, "_");

  var safeSession =
    String(
      session.time ||
      session.title ||
      "CUSTOM"
    )
      .replace(/[^A-Za-z0-9_-]/g, "_");

  var sheetName =
    "MED_" +
    executionId +
    "_" +
    safeResident +
    "_" +
    safeSession +
    "_" +
    String(pageNumber);

  sheet.setName(
    medChart_makeUniqueSheetName(
      ss,
      sheetName
    )
  );

  // ============================================================
  // HEADER
  // ============================================================

  medChart_replacePlaceholder(
    sheet,
    "{{RESIDENT_NAME}}",
    resident.Residents || ""
  );

  medChart_replacePlaceholder(
    sheet,
    "{{MONTH}}",
    medChart_formatMonth(year, month)
  );

  // The template's B6:D7 area is the serving-time display area.
  // B6 is the top-left cell of the merged range.
  var servingTimeText =
    "Serving Time: " +
    String(
      session.title ||
      session.time ||
      ""
    );

  sheet
    .getRange(servingTimeCell)
    .setValue(servingTimeText)
    .setVerticalAlignment("middle");

  // Also replace the placeholder wherever it exists in the header.
  medChart_replacePlaceholder(
    sheet,
    "{{SESSION_TITLE}}",
    session.title ||
      session.time ||
      ""
  );

  // ============================================================
  // PAGE NUMBER — FIXED AT AG32
  // ============================================================

  var safeTotalPages =
    Number(totalPages) > 0
      ? Number(totalPages)
      : 1;

  sheet
    .getRange(pageNumberCell)
    .setValue(
      "Page: " +
      Number(pageNumber || 1) +
      "/" +
      safeTotalPages
    );

  // ============================================================
  // DATE CELLS
  // ============================================================
  // Active/serving day = blank, ready for manual nursing entries.
  // Non-serving day / outside medication period / invalid calendar
  // date = "xxxx" so the template's existing conditional formatting
  // turns the cell grey.
  // ============================================================

  var daysInMonth =
    getDaysInMonth(year, month);

  var dateValues = [];

  for (var day = 1; day <= numberOfDayColumns; day++) {
    var isValidCalendarDay =
      day <= daysInMonth;

    var isServingDay =
      isValidCalendarDay &&
      shouldPrepareMedicineOnDay(
        medications[0],
        year,
        month,
        day
      );

    // We will calculate this separately for every medication row below.
    dateValues.push(
      isValidCalendarDay && isServingDay
        ? ""
        : "xxxx"
    );
  }

  // ============================================================
  // MEDICATION ROWS — START AT ROW 9
  // ============================================================

  for (var i = 0; i < medications.length; i++) {
    var med = medications[i];
    var row = medicineStartRow + i;

    sheet
      .getRange(
        row,
        templateColumns.no
      )
      .setValue(i + 1)
      .setHorizontalAlignment("center")
      .setVerticalAlignment("middle");

    sheet
      .getRange(
        row,
        templateColumns.medicine
      )
      .setValue(
        buildMedicineDescription(med) || ""
      )
      .setWrap(true)
      .setVerticalAlignment("middle");

    sheet
      .getRange(
        row,
        templateColumns.indication
      )
      .setValue(
        med["Indication"] || ""
      )
      .setWrap(true)
      .setVerticalAlignment("middle");

    // "Noted By" is normally stored as a StaffID.
    // Convert it to StaffName for the printed chart.
    var rawStaff =
      med["Noted By"] ||
      med["Ordered By"] ||
      "";

    var staffName = "";

    if (rawStaff) {
      staffName =
        getStaffName(rawStaff) ||
        String(rawStaff);
    }

    sheet
      .getRange(
        row,
        templateColumns.notedBy
      )
      .setValue(staffName)
      .setWrap(true)
      .setVerticalAlignment("middle");

    // Each medication gets its own serving-day calculation.
    var rowDateValues = [];

    for (
      var dayIndex = 1;
      dayIndex <= numberOfDayColumns;
      dayIndex++
    ) {
      var serving =
        dayIndex <= daysInMonth &&
        shouldPrepareMedicineOnDay(
          med,
          year,
          month,
          dayIndex
        );

      rowDateValues.push(
        serving ? "" : "xxxx"
      );
    }

    sheet
      .getRange(
        row,
        firstDayColumn,
        1,
        numberOfDayColumns
      )
      .setValues([rowDateValues]);
  }

  // ============================================================
  // CLEAN UNUSED TEMPLATE TOKENS
  // ============================================================

  medChart_replacePlaceholder(
    sheet,
    "{{NO}}",
    ""
  );

  medChart_replacePlaceholder(
    sheet,
    "{{MEDICINE}}",
    ""
  );

  medChart_replacePlaceholder(
    sheet,
    "{{INDICATION}}",
    ""
  );

  medChart_replacePlaceholder(
    sheet,
    "{{NOTED_BY}}",
    ""
  );

  // If the template uses a {{PAGE}} token anywhere in the footer,
  // replace it too. AG32 remains the authoritative page-number cell.
  medChart_replacePlaceholder(
    sheet,
    "{{PAGE}}",
    Number(pageNumber || 1) + "/" + safeTotalPages
  );

  SpreadsheetApp.flush();

  return sheet;
}


// ============================================================
// PLACEHOLDER HELPERS
// ============================================================

function medChart_findPlaceholderCell(
  sheet,
  placeholder
) {
  return sheet
    .createTextFinder(placeholder)
    .matchEntireCell(true)
    .useRegularExpression(false)
    .findNext();
}


function medChart_replacePlaceholder(
  sheet,
  placeholder,
  value
) {
  var replacement =
    value === null ||
    value === undefined
      ? ""
      : String(value);

  sheet
    .createTextFinder(placeholder)
    .matchEntireCell(true)
    .useRegularExpression(false)
    .replaceAllWith(replacement);
}


// ============================================================
// MONTH / SHEET NAME HELPERS
// ============================================================

function medChart_formatMonth(
  year,
  month
) {
  var date = new Date(
    Number(year),
    Number(month) - 1,
    1
  );

  return Utilities.formatDate(
    date,
    Session.getScriptTimeZone(),
    "MMMM yyyy"
  );
}


function medChart_makeUniqueSheetName(
  ss,
  proposedName
) {
  var base =
    String(
      proposedName || "MedicationChart"
    ).substring(0, 100);

  if (!ss.getSheetByName(base)) {
    return base;
  }

  for (var i = 2; i <= 999; i++) {
    var suffix = "_" + i;

    var candidate =
      base.substring(
        0,
        100 - suffix.length
      ) + suffix;

    if (!ss.getSheetByName(candidate)) {
      return candidate;
    }
  }

  return (
    base.substring(0, 85) +
    "_" +
    Utilities.getUuid().substring(0, 12)
  ).substring(0, 100);
}


// ============================================================
// OPTIONAL TEST
// ============================================================

function testResidentMedicationChartGenerator() {
  var residentID = "AMN-14";
  var year = 2026;
  var month = 9;

  var executionId =
    Utilities.getUuid();

  var report =
    generateResidentMedicationCharts(
      residentID,
      year,
      month,
      executionId
    );

  Logger.log(
    JSON.stringify(
      {
        residentID:
          report.residentID,
        resident:
          report.resident.Residents,
        pages:
          report.sheets.length,
        executionId:
          executionId
      },
      null,
      2
    )
  );
}
